version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  gateway:
    build: ./gateway
    image: gateway:latest
    scale: 16
    environment:
      - NATS_URL=nats://nats:4222
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4 --log-level warning --no-access-log
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - nats

  nats:
    image: nats:2.12-alpine
    command: ["-js", "-sd", "/dev/shm/nats"]
    shm_size: '2g'

  order-service:
    build: ./order
    image: order:latest
    scale: 16
    environment:
      - GATEWAY_URL=http://nginx:80
      - NATS_URL=nats://nats:4222
      - REDIS_SHARDS=order-db-0:6379,order-db-1:6379,order-db-2:6379
    command: python app.py
    env_file:
      - env/order_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - order-db-0
      - order-db-1
      - order-db-2
      - nats

  order-db-0:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  order-db-1:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  order-db-2:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    scale: 16
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_SHARDS=stock-db-0:6379,stock-db-1:6379,stock-db-2:6379
    command: python app.py
    env_file:
      - env/stock_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - stock-db-0
      - stock-db-1
      - stock-db-2
      - nats

  stock-db-0:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-db-1:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-db-2:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: payment:latest
    scale: 16
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_SHARDS=payment-db-0:6379,payment-db-1:6379,payment-db-2:6379
    command: python app.py
    env_file:
      - env/payment_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - payment-db-0
      - payment-db-1
      - payment-db-2
      - nats

  payment-db-0:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-db-1:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-db-2:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
