version: "3"
services:
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway-1
      - gateway-2
      - gateway-3
  gateway-1:
    build: ./gateway
    image: gateway:latest
    environment:
      - NATS_URL=nats://nats:4222
      - ORDER_URL=http://order-service:5000
      - PAYMENT_URL=http://payment-service:5000
      - STOCK_URL=http://stock-service:5000
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 3 --log-level info --no-access-log
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - order-service
      - stock-service
      - payment-service
      - nats

  gateway-2:
    build: ./gateway
    image: gateway:latest
    environment:
      - NATS_URL=nats://nats:4222
      - ORDER_URL=http://order-service:5000
      - PAYMENT_URL=http://payment-service:5000
      - STOCK_URL=http://stock-service:5000
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 2 --log-level info --no-access-log
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - order-service
      - stock-service
      - payment-service
      - nats

  gateway-3:
    build: ./gateway
    image: gateway:latest
    environment:
      - NATS_URL=nats://nats:4222
      - ORDER_URL=http://order-service:5000
      - PAYMENT_URL=http://payment-service:5000
      - STOCK_URL=http://stock-service:5000
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 2 --log-level info --no-access-log
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - order-service
      - stock-service
      - payment-service
      - nats

  nats:
    image: nats:2.12-alpine
    command: ["--js"]
    ports:
      - "4222:4222"

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://nginx:80
      - NATS_URL=nats://nats:4222
    command: python app.py
    env_file:
      - env/order_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - order-db
      - nats

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    environment:
      - NATS_URL=nats://nats:4222
    command: python app.py
    env_file:
      - env/stock_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - stock-db
      - nats

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: user:latest
    environment:
      - NATS_URL=nats://nats:4222
    command: python app.py
    env_file:
      - env/payment_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - payment-db
      - nats

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
