version: "3"
services:
  gateway:
    build: ./gateway
    image: gateway:latest
    environment:
      - NATS_URL=nats://nats:4222
      - ORDER_URL=http://order-service:5000
      - PAYMENT_URL=http://payment-service:5000
      - STOCK_URL=http://stock-service:5000
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 2 --log-level info --no-access-log
    volumes:
      - ./common:/app/common:ro
    ports:
      - "8000:8000"
    depends_on:
      - order-service
      - stock-service
      - payment-service
      - nats

  nats:
    image: nats:2.12-alpine
    command: ["--js"]
    ports:
      - "4222:4222"

  order-service:
    build:
      context: .
      dockerfile: order/Dockerfile
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:8000
      - NATS_URL=nats://nats:4222
    command: python app.py
    env_file:
      - env/order_redis.env
      - env/order_lock_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - order-db
      - order-lock-db
      - nats

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  order-lock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 128mb


  stock-service:
    build:
      context: .
      dockerfile: stock/Dockerfile
    image: stock:latest
    environment:
      - NATS_URL=nats://nats:4222
    command: python app.py
    env_file:
      - env/stock_redis.env
      - env/stock_lock_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - stock-db
      - stock-lock-db
      - nats

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-lock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 128mb

  payment-service:
    build:
      context: .
      dockerfile: payment/Dockerfile
    image: user:latest
    environment:
      - NATS_URL=nats://nats:4222
    command: python app.py
    env_file:
      - env/payment_redis.env
      - env/payment_lock_redis.env
    volumes:
      - ./common:/app/common:ro
    depends_on:
      - payment-db
      - payment-lock-db
      - nats

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-lock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 128mb
