name: Deploy to Server

on:
  push:
    branches:
      - RabbitMQ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart Docker Containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/dds-project
            sudo ./dc.sh down
            git fetch --all
            git reset --hard origin/RabbitMQ
            git pull
            sudo ./dc.sh up
